services:
  db:
    container_name: hjam-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  back:
    container_name: hjam-back
    build: ./hackathon-jam-back
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/src/app/hackathon-jam-back
    command: air ./main.go -i 0.0.0.0
  front:
    container_name: hjam-front
    build: .
    ports:
      - '80:3000'
    volumes:
      - .:/hackathon-jam-front
volumes:
  postgres-db: